//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.13 at 12:37:48 πμ EET 
//


package com.cleargist.catalog.deals.entity.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for dealType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dealType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dealId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dealURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dealDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dealTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="siteId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="siteCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="siteCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="siteCategories" type="{}stringListType" minOccurs="0"/>
 *         &lt;element name="businessName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="businessAddress" type="{}addressListType" minOccurs="0"/>
 *         &lt;element name="couponPurchaseStartingDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="couponPurchaseEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="couponRedemptionStartingDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="couponRedemptionEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="validDates" type="{}stringListType" minOccurs="0"/>
 *         &lt;element name="hasBlockerDates" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="initialPrice" type="{}priceType"/>
 *         &lt;element name="dealPrice" type="{}priceType"/>
 *         &lt;element name="numberOfCouponsSold" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="category">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ArtsAndEntertainment"/>
 *               &lt;enumeration value="Automotive"/>
 *               &lt;enumeration value="BeautyAndSpas"/>
 *               &lt;enumeration value="Education"/>
 *               &lt;enumeration value="FoodAndDrink"/>
 *               &lt;enumeration value="HealthAndFitness"/>
 *               &lt;enumeration value="HomeServices"/>
 *               &lt;enumeration value="Nightlife"/>
 *               &lt;enumeration value="Pets"/>
 *               &lt;enumeration value="ProfessionalServices"/>
 *               &lt;enumeration value="Restaurants"/>
 *               &lt;enumeration value="Shopping"/>
 *               &lt;enumeration value="Travel"/>
 *               &lt;enumeration value="Unknown"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="subCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isLuxuryBusiness" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasMultiplePrices" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="requiresStoreVisit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="requiresMoreToPay" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="maxCouponsPerPerson" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="minCouponsForActivation" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="requiresPhoneReservation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isOnePersonCoupon" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isSingleVisitCoupon" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasExtraDiscounts" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isComboDeal" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasOptions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasVideo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="numberOfHotelNights" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dealType", propOrder = {
    "dealId",
    "dealURL",
    "dealDescription",
    "dealTitle",
    "siteId",
    "siteCountry",
    "siteCity",
    "siteCategories",
    "businessName",
    "businessAddress",
    "couponPurchaseStartingDate",
    "couponPurchaseEndDate",
    "couponRedemptionStartingDate",
    "couponRedemptionEndDate",
    "validDates",
    "hasBlockerDates",
    "initialPrice",
    "dealPrice",
    "numberOfCouponsSold",
    "category",
    "subCategory",
    "isLuxuryBusiness",
    "hasMultiplePrices",
    "requiresStoreVisit",
    "requiresMoreToPay",
    "maxCouponsPerPerson",
    "minCouponsForActivation",
    "requiresPhoneReservation",
    "isOnePersonCoupon",
    "isSingleVisitCoupon",
    "hasExtraDiscounts",
    "isComboDeal",
    "hasOptions",
    "hasVideo",
    "numberOfHotelNights"
})
public class DealType {

    @XmlElement(required = true)
    protected String dealId;
    @XmlElement(required = true)
    protected String dealURL;
    protected String dealDescription;
    protected String dealTitle;
    @XmlElement(required = true)
    protected String siteId;
    @XmlElement(required = true)
    protected String siteCountry;
    @XmlElement(required = true)
    protected String siteCity;
    @XmlList
    protected List<String> siteCategories;
    @XmlElement(required = true)
    protected String businessName;
    protected AddressListType businessAddress;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar couponPurchaseStartingDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar couponPurchaseEndDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar couponRedemptionStartingDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar couponRedemptionEndDate;
    @XmlList
    protected List<String> validDates;
    protected Boolean hasBlockerDates;
    @XmlElement(required = true)
    protected BigDecimal initialPrice;
    @XmlElement(required = true)
    protected BigDecimal dealPrice;
    protected BigInteger numberOfCouponsSold;
    @XmlElement(required = true, defaultValue = "Unknown")
    protected String category;
    protected String subCategory;
    protected Boolean isLuxuryBusiness;
    protected Boolean hasMultiplePrices;
    protected Boolean requiresStoreVisit;
    protected Boolean requiresMoreToPay;
    protected BigInteger maxCouponsPerPerson;
    protected BigInteger minCouponsForActivation;
    protected Boolean requiresPhoneReservation;
    protected Boolean isOnePersonCoupon;
    protected Boolean isSingleVisitCoupon;
    protected Boolean hasExtraDiscounts;
    protected Boolean isComboDeal;
    protected Boolean hasOptions;
    protected Boolean hasVideo;
    protected BigInteger numberOfHotelNights;

    /**
     * Gets the value of the dealId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealId() {
        return dealId;
    }

    /**
     * Sets the value of the dealId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealId(String value) {
        this.dealId = value;
    }

    /**
     * Gets the value of the dealURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealURL() {
        return dealURL;
    }

    /**
     * Sets the value of the dealURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealURL(String value) {
        this.dealURL = value;
    }

    /**
     * Gets the value of the dealDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealDescription() {
        return dealDescription;
    }

    /**
     * Sets the value of the dealDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealDescription(String value) {
        this.dealDescription = value;
    }

    /**
     * Gets the value of the dealTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealTitle() {
        return dealTitle;
    }

    /**
     * Sets the value of the dealTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealTitle(String value) {
        this.dealTitle = value;
    }

    /**
     * Gets the value of the siteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * Sets the value of the siteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteId(String value) {
        this.siteId = value;
    }

    /**
     * Gets the value of the siteCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteCountry() {
        return siteCountry;
    }

    /**
     * Sets the value of the siteCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteCountry(String value) {
        this.siteCountry = value;
    }

    /**
     * Gets the value of the siteCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteCity() {
        return siteCity;
    }

    /**
     * Sets the value of the siteCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteCity(String value) {
        this.siteCity = value;
    }

    /**
     * Gets the value of the siteCategories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the siteCategories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSiteCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSiteCategories() {
        if (siteCategories == null) {
            siteCategories = new ArrayList<String>();
        }
        return this.siteCategories;
    }

    /**
     * Gets the value of the businessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * Sets the value of the businessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessName(String value) {
        this.businessName = value;
    }

    /**
     * Gets the value of the businessAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressListType }
     *     
     */
    public AddressListType getBusinessAddress() {
        return businessAddress;
    }

    /**
     * Sets the value of the businessAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressListType }
     *     
     */
    public void setBusinessAddress(AddressListType value) {
        this.businessAddress = value;
    }

    /**
     * Gets the value of the couponPurchaseStartingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCouponPurchaseStartingDate() {
        return couponPurchaseStartingDate;
    }

    /**
     * Sets the value of the couponPurchaseStartingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCouponPurchaseStartingDate(XMLGregorianCalendar value) {
        this.couponPurchaseStartingDate = value;
    }

    /**
     * Gets the value of the couponPurchaseEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCouponPurchaseEndDate() {
        return couponPurchaseEndDate;
    }

    /**
     * Sets the value of the couponPurchaseEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCouponPurchaseEndDate(XMLGregorianCalendar value) {
        this.couponPurchaseEndDate = value;
    }

    /**
     * Gets the value of the couponRedemptionStartingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCouponRedemptionStartingDate() {
        return couponRedemptionStartingDate;
    }

    /**
     * Sets the value of the couponRedemptionStartingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCouponRedemptionStartingDate(XMLGregorianCalendar value) {
        this.couponRedemptionStartingDate = value;
    }

    /**
     * Gets the value of the couponRedemptionEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCouponRedemptionEndDate() {
        return couponRedemptionEndDate;
    }

    /**
     * Sets the value of the couponRedemptionEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCouponRedemptionEndDate(XMLGregorianCalendar value) {
        this.couponRedemptionEndDate = value;
    }

    /**
     * Gets the value of the validDates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validDates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidDates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidDates() {
        if (validDates == null) {
            validDates = new ArrayList<String>();
        }
        return this.validDates;
    }

    /**
     * Gets the value of the hasBlockerDates property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasBlockerDates() {
        return hasBlockerDates;
    }

    /**
     * Sets the value of the hasBlockerDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasBlockerDates(Boolean value) {
        this.hasBlockerDates = value;
    }

    /**
     * Gets the value of the initialPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInitialPrice() {
        return initialPrice;
    }

    /**
     * Sets the value of the initialPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInitialPrice(BigDecimal value) {
        this.initialPrice = value;
    }

    /**
     * Gets the value of the dealPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDealPrice() {
        return dealPrice;
    }

    /**
     * Sets the value of the dealPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDealPrice(BigDecimal value) {
        this.dealPrice = value;
    }

    /**
     * Gets the value of the numberOfCouponsSold property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfCouponsSold() {
        return numberOfCouponsSold;
    }

    /**
     * Sets the value of the numberOfCouponsSold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfCouponsSold(BigInteger value) {
        this.numberOfCouponsSold = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the subCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCategory() {
        return subCategory;
    }

    /**
     * Sets the value of the subCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCategory(String value) {
        this.subCategory = value;
    }

    /**
     * Gets the value of the isLuxuryBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLuxuryBusiness() {
        return isLuxuryBusiness;
    }

    /**
     * Sets the value of the isLuxuryBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLuxuryBusiness(Boolean value) {
        this.isLuxuryBusiness = value;
    }

    /**
     * Gets the value of the hasMultiplePrices property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasMultiplePrices() {
        return hasMultiplePrices;
    }

    /**
     * Sets the value of the hasMultiplePrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasMultiplePrices(Boolean value) {
        this.hasMultiplePrices = value;
    }

    /**
     * Gets the value of the requiresStoreVisit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresStoreVisit() {
        return requiresStoreVisit;
    }

    /**
     * Sets the value of the requiresStoreVisit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresStoreVisit(Boolean value) {
        this.requiresStoreVisit = value;
    }

    /**
     * Gets the value of the requiresMoreToPay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresMoreToPay() {
        return requiresMoreToPay;
    }

    /**
     * Sets the value of the requiresMoreToPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresMoreToPay(Boolean value) {
        this.requiresMoreToPay = value;
    }

    /**
     * Gets the value of the maxCouponsPerPerson property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxCouponsPerPerson() {
        return maxCouponsPerPerson;
    }

    /**
     * Sets the value of the maxCouponsPerPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxCouponsPerPerson(BigInteger value) {
        this.maxCouponsPerPerson = value;
    }

    /**
     * Gets the value of the minCouponsForActivation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinCouponsForActivation() {
        return minCouponsForActivation;
    }

    /**
     * Sets the value of the minCouponsForActivation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinCouponsForActivation(BigInteger value) {
        this.minCouponsForActivation = value;
    }

    /**
     * Gets the value of the requiresPhoneReservation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresPhoneReservation() {
        return requiresPhoneReservation;
    }

    /**
     * Sets the value of the requiresPhoneReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresPhoneReservation(Boolean value) {
        this.requiresPhoneReservation = value;
    }

    /**
     * Gets the value of the isOnePersonCoupon property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsOnePersonCoupon() {
        return isOnePersonCoupon;
    }

    /**
     * Sets the value of the isOnePersonCoupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOnePersonCoupon(Boolean value) {
        this.isOnePersonCoupon = value;
    }

    /**
     * Gets the value of the isSingleVisitCoupon property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSingleVisitCoupon() {
        return isSingleVisitCoupon;
    }

    /**
     * Sets the value of the isSingleVisitCoupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSingleVisitCoupon(Boolean value) {
        this.isSingleVisitCoupon = value;
    }

    /**
     * Gets the value of the hasExtraDiscounts property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasExtraDiscounts() {
        return hasExtraDiscounts;
    }

    /**
     * Sets the value of the hasExtraDiscounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasExtraDiscounts(Boolean value) {
        this.hasExtraDiscounts = value;
    }

    /**
     * Gets the value of the isComboDeal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsComboDeal() {
        return isComboDeal;
    }

    /**
     * Sets the value of the isComboDeal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsComboDeal(Boolean value) {
        this.isComboDeal = value;
    }

    /**
     * Gets the value of the hasOptions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasOptions() {
        return hasOptions;
    }

    /**
     * Sets the value of the hasOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasOptions(Boolean value) {
        this.hasOptions = value;
    }

    /**
     * Gets the value of the hasVideo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasVideo() {
        return hasVideo;
    }

    /**
     * Sets the value of the hasVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasVideo(Boolean value) {
        this.hasVideo = value;
    }

    /**
     * Gets the value of the numberOfHotelNights property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfHotelNights() {
        return numberOfHotelNights;
    }

    /**
     * Sets the value of the numberOfHotelNights property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfHotelNights(BigInteger value) {
        this.numberOfHotelNights = value;
    }

}
