//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.31 at 10:12:51 μμ EEST 
//


package com.cleargist.data.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mainActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="mainActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PURCHASE"/>
 *     &lt;enumeration value="ADD_TO_CART"/>
 *     &lt;enumeration value="ITEM_PAGE_VIEW"/>
 *     &lt;enumeration value="HOME_PAGE_VIEW"/>
 *     &lt;enumeration value="CATEGORY_PAGE_VIEW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "mainActionType")
@XmlEnum
public enum MainActionType {

    PURCHASE,
    ADD_TO_CART,
    ITEM_PAGE_VIEW,
    HOME_PAGE_VIEW,
    CATEGORY_PAGE_VIEW;

    public String value() {
        return name();
    }

    public static MainActionType fromValue(String v) {
        return valueOf(v);
    }

}
